### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tzmfreedom** [tzmfreedom/yasd#1]
* [x] query
* [x] insert
* [x] update
* [x] delete
* [x] undelete
* [ ] parallel execution
* [x] yaml mapping
* [ ] dockerize
* [ ] from csv, tsv, fixwidth
* [ ] to csv, tsv, fixwidth, sql
* [x] astar query describe
* [x] environment variable
* [x] encryption?
* [x] encoding support
